---

# matrix
dist: focal
os: linux
language: python
python:
  - 3.9
  - 3.8
  - 3.7
  - 3.6
jobs:
  include:
    - stage: deploy
      script: ./deploy.sh
      python: 3.9
# test stage
script:
  - tox
# stage ordering
stages:
  - test
  - name: deploy
    if: tag IS present AND (tag =~ ^v)
# shared
install:
  - pip install tox-travis
  - pip install wheel
  - pip install twine
env:
  # TODO: configure deployment credentials
  global: []
