[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "clickable_util"
author = "Laurent Almeras"
author-email = "lalmeras@gmail.com"
home-page = "https://github.com/lalmeras/clickable"
classifiers = ["License :: OSI Approved :: MIT License"]

